[package]
name = "causal_grav"
version = "0.1.0"
edition = "2021"

[dependencies]
graphics = { path = "../../graphics_wgpu" }
lin-alg = { package = "lin-alg2", path = "../../lin_alg" }
egui = "^0.29.1"

rand = "^0.8.5"

# cudarc = { version = "^0.12.1", features=["cuda-12060"] }